name: Esegui GOOGLE SHEETS UPDATE

on:
  workflow_dispatch: # Ti permette di avviarlo manualmente per testare se funziona



jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r ./req/requirements.txt

      - name: Aggiorna Google Sheets 1
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID_WAR }}
        run: python ./scripts/update_war.py

      - name: Aggiorna Google Sheets 2
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID_EVENTS }}
        run: python ./scripts/update_events.py
