name: Esegui WAR Update

on:
  schedule:
    # 06:00 UTC = 07:00 Italiane (Ora solare)
    - cron: '8 22 25 * *'
  workflow_dispatch: # Ti permette di avviarlo manualmente per testare se funziona

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui script war
        # Se il file clan_games.py Ã¨ in una sottocartella, aggiungi il percorso (es. scripts/clan_games.py)
        env:
          # Qui colleghi il Secret di GitHub alla variabile d'ambiente del sistema
          COC_EMAIL: ${{ secrets.COC_EMAIL }}
          COC_PASSWORD: ${{ secrets.COC_PASSWORD }}
          CLAN_TAG: ${{ secrets.CLAN_TAG }}
        run: python war.py

      - name: Salva modifiche Excel
        run: |-
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.xlsx
          # Il comando commit non fallisce se non ci sono modifiche grazie a || echo
          git commit -m "Update WAR data - $(date +'%Y-%m-%d')" || echo "Nessuna modifica da salvare"
          git push
